// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuteQAaLwjV4Ir2GNNUQsOuPNh8fVWf-w',
    appId: '1:451109908749:web:03e920d74aff9f9e324044',
    messagingSenderId: '451109908749',
    projectId: 'tiktok-fb-proj',
    authDomain: 'tiktok-fb-proj.firebaseapp.com',
    storageBucket: 'tiktok-fb-proj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdrD4eNUwpVLCZV9GqRq_lpHRXXYjDFhc',
    appId: '1:451109908749:android:97417901f153b38a324044',
    messagingSenderId: '451109908749',
    projectId: 'tiktok-fb-proj',
    storageBucket: 'tiktok-fb-proj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgtqYUDRlOQcyCqiBQgowyMgqRofzjmZs',
    appId: '1:451109908749:ios:ca43679f07a1743d324044',
    messagingSenderId: '451109908749',
    projectId: 'tiktok-fb-proj',
    storageBucket: 'tiktok-fb-proj.appspot.com',
    androidClientId: '451109908749-70d4akke063jt81jephos4h9eqju0rud.apps.googleusercontent.com',
    iosClientId: '451109908749-vj0618ff9r4asesgv9te9m0p8bufeu46.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgtqYUDRlOQcyCqiBQgowyMgqRofzjmZs',
    appId: '1:451109908749:ios:ca43679f07a1743d324044',
    messagingSenderId: '451109908749',
    projectId: 'tiktok-fb-proj',
    storageBucket: 'tiktok-fb-proj.appspot.com',
    androidClientId: '451109908749-70d4akke063jt81jephos4h9eqju0rud.apps.googleusercontent.com',
    iosClientId: '451109908749-vj0618ff9r4asesgv9te9m0p8bufeu46.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktokClone',
  );
}
